# Generated by Django 3.1.5 on 2021-02-11 18:45

from django.db import migrations, models
import django.db.models.deletion
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20210210_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yt',
            name='video',
            field=models.ForeignKey(blank=True, default=videos.models.Video, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.video'),
        ),
    ]
